services:
  # Backend Django
  backend:
    build: ./backend
    container_name: rh-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - rh-network

  # Frontend React
  frontend:
    build: ./frontend
    container_name: rh-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - rh-network

networks:
  rh-network:
    driver: bridge
